<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="testSingleAPI"
           tests="9"
           failures="2"
           errors="0"
           skipped="0"
           time="0.762">
  <properties />
            <testcase name="testLoginFault1" time="0.091" classname="com.edu.qgSingleAPI.LoginTest">
                <failure type="java.lang.Exception"
                  message="expectedValue doesn&apos;t match actualValue,actual Value is :success; expected Value is :用户名或者密码错误"
              >
<![CDATA[java.lang.Exception: expectedValue doesn't match actualValue,actual Value is :success; expected Value is :用户名或者密码错误
  com.edu.utils.Checker.verify(Checker.java:59)
  com.edu.utils.Checker.verifyXpath(Checker.java:45)
  com.edu.qgSingleAPI.LoginTest.testLoginFault1(LoginTest.java:55)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
            <testcase name="testLoginFault8" time="0.072" classname="com.edu.qgSingleAPI.LoginTest">
                <failure type="java.lang.Exception"
                  message="expectedValue doesn&apos;t match actualValue,actual Value is :用户名或者密码错误; expected Value is :用户名或密码错误"
              >
<![CDATA[java.lang.Exception: expectedValue doesn't match actualValue,actual Value is :用户名或者密码错误; expected Value is :用户名或密码错误
  com.edu.utils.Checker.verify(Checker.java:59)
  com.edu.utils.Checker.verifyXpath(Checker.java:45)
  com.edu.qgSingleAPI.LoginTest.testLogin(LoginTest.java:31)
  com.edu.qgSingleAPI.LoginTest.testLoginFault8(LoginTest.java:127)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.base/java.lang.reflect.Method.invoke(Method.java:564)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
  org.testng.TestRunner.privateRun(TestRunner.java:648)
  org.testng.TestRunner.run(TestRunner.java:505)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
  org.testng.SuiteRunner.run(SuiteRunner.java:364)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
  org.testng.TestNG.runSuites(TestNG.java:1049)
  org.testng.TestNG.run(TestNG.java:1017)
  org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
  org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
  org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
      </failure>

          </testcase>
  
  
            <testcase name="testLoginFault2" time="0.086" classname="com.edu.qgSingleAPI.LoginTest" />
                <testcase name="testLoginFault6" time="0.085" classname="com.edu.qgSingleAPI.LoginTest" />
                <testcase name="testLoginFault3" time="0.078" classname="com.edu.qgSingleAPI.LoginTest" />
                <testcase name="testLoginFault7" time="0.100" classname="com.edu.qgSingleAPI.LoginTest" />
                <testcase name="testLoginSuccess" time="0.089" classname="com.edu.qgSingleAPI.LoginTest" />
                <testcase name="testLoginFault5" time="0.084" classname="com.edu.qgSingleAPI.LoginTest" />
                <testcase name="testLoginFault4" time="0.077" classname="com.edu.qgSingleAPI.LoginTest" />
      
</testsuite>
