<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-MQRFOO8" failures="0" tests="9" name="com.edu.qgSingleAPI.LoginTest" time="2.703" errors="2" timestamp="25 12月 2018 06:27:59 GMT" skipped="0">
  <testcase classname="com.edu.qgSingleAPI.LoginTest" name="testLoginFault4" time="0.114"/>
  <testcase classname="com.edu.qgSingleAPI.LoginTest" name="testLoginFault3" time="0.108"/>
  <testcase classname="com.edu.qgSingleAPI.LoginTest" name="testLoginSuccess" time="0.131"/>
  <testcase classname="com.edu.qgSingleAPI.LoginTest" name="testLoginFault7" time="0.102"/>
  <testcase classname="com.edu.qgSingleAPI.LoginTest" name="testLoginFault1" time="0.548">
    <error message="expectedValue doesn&#039;t match actualValue,actual Value is :success; expected Value is :用户名或者密码错误" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: expectedValue doesn't match actualValue,actual Value is :success; expected Value is :用户名或者密码错误
at com.edu.utils.Checker.verify(Checker.java:59)
at com.edu.utils.Checker.verifyXpath(Checker.java:45)
at com.edu.qgSingleAPI.LoginTest.testLoginFault1(LoginTest.java:55)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testLoginFault1 -->
  <testcase classname="com.edu.qgSingleAPI.LoginTest" name="testLoginFault5" time="1.378"/>
  <testcase classname="com.edu.qgSingleAPI.LoginTest" name="testLoginFault8" time="0.116">
    <error message="expectedValue doesn&#039;t match actualValue,actual Value is :用户名或者密码错误; expected Value is :用户名或密码错误" type="java.lang.Exception">
      <![CDATA[java.lang.Exception: expectedValue doesn't match actualValue,actual Value is :用户名或者密码错误; expected Value is :用户名或密码错误
at com.edu.utils.Checker.verify(Checker.java:59)
at com.edu.utils.Checker.verifyXpath(Checker.java:45)
at com.edu.qgSingleAPI.LoginTest.testLogin(LoginTest.java:31)
at com.edu.qgSingleAPI.LoginTest.testLoginFault8(LoginTest.java:127)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- testLoginFault8 -->
  <testcase classname="com.edu.qgSingleAPI.LoginTest" name="testLoginFault2" time="0.098"/>
  <testcase classname="com.edu.qgSingleAPI.LoginTest" name="testLoginFault6" time="0.108"/>
</testsuite> <!-- com.edu.qgSingleAPI.LoginTest -->
